### ISSUE TITLE
run_script failing to parse int for --vus

### ISSUE THREAD

**Issue by robertb724** [grafana/chaostoolkit-k6#7]
I have been attempting to use this to run k6 scripts. I was having issues with error

```
time="2021-10-28T16:29:08-04:00" level=error msg="invalid argument \"iet\" for \"-u, --vus\" flag: strconv.ParseInt: parsing \"iet\": invalid syntax"
```

I am able to reproduce this issue by running the example test: https://github.com/grafana/chaostoolkit-k6/blob/main/examples/experiment.json

Steps to reproduce: 
1. install `chaos` cli
2. install `k6` cli
3. download above script
4. run command `chaos run experiment.json`

**Comment by heatonmatthew** [comment]
Based on the source code, it looks like this is calling `_runScript` with a flag of `-quiet` instead of `--quiet`.
